console.log('a');
let sererStudy = "fs.readFile 전 초기값";
//call back은 거의 쓰지 않음 -> 콜백 지옥 때문에

/** 
 * 성공 resolve then
 * 실패 reject catch
*/

/**
 * async await은 오류 처리를 못해주니까
 * try catch로 해결해줌
 */

